In [2]:
import pandas as pd
import numpy as np
import requests as rq
import json as js

In [3]:
!pip install tweepy

Requirement already satisfied: tweepy in c:\users\puspa\anaconda3\lib\site-packages (3.9.0)
Requirement already satisfied: six>=1.10.0 in c:\users\puspa\anaconda3\lib\site-packages (from tweepy) (1.12.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\puspa\anaconda3\lib\site-packages (from tweepy) (1.3.0)
Requirement already satisfied: requests[socks]>=2.11.1 in c:\users\puspa\anaconda3\lib\site-packages (from tweepy) (2.22.0)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\puspa\anaconda3\lib\site-packages (from requests-oauthlib>=0.7.0->tweepy) (3.1.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\puspa\anaconda3\lib\site-packages (from requests[socks]>=2.11.1->tweepy) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\puspa\anaconda3\lib\site-packages (from requests[socks]>=2.11.1->tweepy) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\puspa\anaconda3\lib\site-packages (from requests[socks]>=2.11.1->tweepy) (1.24.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\puspa\anaconda3\lib\site-packages (from requests[socks]>=2.11.1->tweepy) (2019.9.11)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6; extra == "socks" in c:\users\puspa\anaconda3\lib\site-packages (from requests[socks]>=2.11.1->tweepy) (1.7.1)

In [4]:
import tweepy

In [5]:
consumer_key = 'J2TX0JearjjYeXleadTUhPyCQ'
consumer_secret = 'GKfGOYigtkkIqCbNBZrLLv9bWp9p4fSdArYNYx5LnG3jkOBJJu'
access_token = '75370479-OzdksulPQv3A23A3Ax93a8pHaWHeQM4MPLNChaIJJ'
access_secret = 'ez6hWnuwNE5FsNBeofE208mEbPfbvvm7JG7zLAlcLCqNG'

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_secret)

#api = tweepy.API(auth)
api = tweepy.API(auth_handler=auth, wait_on_rate_limit=True, wait_on_rate_limit_notify=True)

In [6]:
from __future__ import print_function
import getopt
import logging
import os
import sys

In [7]:
import requests

In [8]:
r = requests.get('https://d17h27t6h515a5.cloudfront.net/topher/2017/August/599fd2ad_image-predictions/image-predictions.tsv', auth=('user', 'pass'))

In [9]:
r.status_code

200

In [10]:
r.headers['content-type']

'text/tab-separated-values; charset=utf-8'

In [11]:
r.encoding

'utf-8'

In [13]:
import csv
df=pd.DataFrame()
wrapper = csv.reader(r.text.strip().split('\n'))
list_of_tuples = list(map(tuple, wrapper))

In [14]:
list_of_tuples[0]

('tweet_id\tjpg_url\timg_num\tp1\tp1_conf\tp1_dog\tp2\tp2_conf\tp2_dog\tp3\tp3_conf\tp3_dog',)

In [15]:
df = pd.DataFrame(list(list_of_tuples))

In [16]:
df

                                                      0
0     tweet_id\tjpg_url\timg_num\tp1\tp1_conf\tp1_do...
1     666020888022790149\thttps://pbs.twimg.com/medi...
2     666029285002620928\thttps://pbs.twimg.com/medi...
3     666033412701032449\thttps://pbs.twimg.com/medi...
4     666044226329800704\thttps://pbs.twimg.com/medi...
...                                                 ...
2071  891327558926688256\thttps://pbs.twimg.com/medi...
2072  891689557279858688\thttps://pbs.twimg.com/medi...
2073  891815181378084864\thttps://pbs.twimg.com/medi...
2074  892177421306343426\thttps://pbs.twimg.com/medi...
2075  892420643555336193\thttps://pbs.twimg.com/medi...

[2076 rows x 1 columns]

In [17]:
df = df[0].str.split('\t',expand=True)

In [18]:
new_header = df.iloc[0] #grab the first row for the header
df = df[1:] #take the data less the header row
df.columns = new_header

In [19]:
df.head(2)

,tweet_id,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog
1,666020888022790149,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,1,Welsh_springer_spaniel,0.465074,True,collie,0.156665,True,Shetland_sheepdog,0.0614285,True
2,666029285002620928,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,1,redbone,0.506826,True,miniature_pinscher,0.07419169999999999,True,Rhodesian_ridgeback,0.07201,True

In [20]:
tweet = api.get_status(666020888022790149)
print(tweet.text)

Here we have a Japanese Irish Setter. Lost eye in Vietnam (?). Big fan of relaxing on stair. 8/10 would pet https://t.co/BLDqew2Ijj

In [45]:
tweet_ids = df['tweet_id']

In [46]:
import tweepy
from tweepy import OAuthHandler
import json
from timeit import default_timer as timer

In [47]:

len(tweet_ids)

# Query Twitter's API for JSON data for each tweet ID in the Twitter archive
count = 0
fails_dict = {}
start = timer()
# Save each tweet's returned JSON as a new line in a .txt file
with open('tweet_json.txt', 'w') as outfile:
    # This loop will likely take 20-30 minutes to run because of Twitter's rate limit
    for tweet_id in tweet_ids:
        count += 1
        print(str(count) + ": " + str(tweet_id))
        try:
            tweet = api.get_status(tweet_id, tweet_mode='extended')
            print("Success")
            json.dump(tweet._json, outfile)
            outfile.write('\n')
        except tweepy.TweepError as e:
            print("Fail")
            fails_dict[tweet_id] = e
            pass
end = timer()
print(end - start)
print(fails_dict)

1: 666020888022790149
Success
2: 666029285002620928
Success
3: 666033412701032449
Success
4: 666044226329800704
Success
5: 666049248165822465
Success
6: 666050758794694657
Success
7: 666051853826850816
Success
8: 666055525042405380
Success
9: 666057090499244032
Success
10: 666058600524156928
Success
11: 666063827256086533
Success
12: 666071193221509120
Success
13: 666073100786774016
Success
14: 666082916733198337
Success
15: 666094000022159362
Success
16: 666099513787052032
Success
17: 666102155909144576
Success
18: 666104133288665088
Success
19: 666268910803644416
Success
20: 666273097616637952
Success
21: 666287406224695296
Success
22: 666293911632134144
Success
23: 666337882303524864
Success
24: 666345417576210432
Success
25: 666353288456101888
Success
26: 666362758909284353
Success
27: 666373753744588802
Success
28: 666396247373291520
Success
29: 666407126856765440
Success
30: 666411507551481857
Success
31: 666418789513326592
Success
32: 666421158376562688
Success
33: 666428276349472768
Success
34: 666430724426358785
Success
35: 666435652385423360
Success
36: 666437273139982337
Success
37: 666447344410484738
Success
38: 666454714377183233
Success
39: 666644823164719104
Success
40: 666649482315059201
Success
41: 666691418707132416
Success
42: 666701168228331520
Success
43: 666739327293083650
Success
44: 666776908487630848
Success
45: 666781792255496192
Success
46: 666786068205871104
Success
47: 666804364988780544
Success
48: 666817836334096384
Success
49: 666826780179869698
Success
50: 666835007768551424
Success
51: 666837028449972224
Success
52: 666983947667116034
Success
53: 666996132027977728
Success
54: 667012601033924608
Success
55: 667044094246576128
Success
56: 667062181243039745
Success
57: 667065535570550784
Success
58: 667073648344346624
Success
59: 667090893657276420
Success
60: 667119796878725120
Success
61: 667138269671505920
Success
62: 667152164079423490
Success
63: 667160273090932737
Success
64: 667165590075940865
Success
65: 667171260800061440
Success
66: 667174963120574464
Success
67: 667176164155375616
Success
68: 667177989038297088
Success
69: 667182792070062081
Success
70: 667188689915760640
Success
71: 667192066997374976
Success
72: 667200525029539841
Success
73: 667211855547486208
Success
74: 667369227918143488
Success
75: 667393430834667520
Success
76: 667405339315146752
Success
77: 667435689202614272
Success
78: 667437278097252352
Success
79: 667443425659232256
Success
80: 667453023279554560
Success
81: 667455448082227200
Success
82: 667470559035432960
Success
83: 667491009379606528
Success
84: 667495797102141441
Success
85: 667502640335572993
Success
86: 667509364010450944
Success
87: 667517642048163840
Success
88: 667524857454854144
Success
89: 667530908589760512
Success
90: 667534815156183040
Success
91: 667538891197542400
Success
92: 667544320556335104
Success
93: 667546741521195010
Success
94: 667549055577362432
Success
95: 667550882905632768
Success
96: 667550904950915073
Success
97: 667724302356258817
Success
98: 667728196545200128
Success
99: 667766675769573376
Success
100: 667773195014021121
Success
101: 667782464991965184
Success
102: 667793409583771648
Success
103: 667801013445750784
Success
104: 667806454573760512
Success
105: 667832474953625600
Success
106: 667861340749471744
Success
107: 667866724293877760
Success
108: 667873844930215936
Success
109: 667878741721415682
Success
110: 667885044254572545
Success
111: 667886921285246976
Success
112: 667902449697558528
Success
113: 667911425562669056
Success
114: 667915453470232577
Success
115: 667924896115245057
Success
116: 667937095915278337
Success
117: 668113020489474048
Success
118: 668142349051129856
Success
119: 668154635664932864
Success
120: 668171859951755264
Success
121: 668190681446379520
Success
122: 668204964695683073
Success
123: 668221241640230912
Success
124: 668226093875376128
Success
125: 668237644992782336
Success
126: 668248472370458624
Success
127: 668256321989451776
Success
128: 668268907921326080
Success
129: 668274247790391296
Success
130: 668286279830867968
Success
131: 668291999406125056
Success
132: 668297328638447616
Success
133: 668466899341221888
Success
134: 668480044826800133
Success
135: 668484198282485761
Success
136: 668496999348633600
Success
137: 668507509523615744
Success
138: 668528771708952576
Success
139: 668537837512433665
Success
140: 668542336805281792
Success
141: 668544745690562560
Success
142: 668567822092664832
Success
143: 668614819948453888
Success
144: 668620235289837568
Success
145: 668623201287675904
Success
146: 668625577880875008
Success
147: 668627278264475648
Success
148: 668631377374486528
Success
149: 668633411083464705
Success
150: 668636665813057536
Success
151: 668641109086707712
Success
152: 668643542311546881
Success
153: 668645506898350081
Success
154: 668655139528511488
Success
155: 668779399630725120
Success
156: 668815180734689280
Success
157: 668826086256599040
Success
158: 668852170888998912
Success
159: 668872652652679168
Success
160: 668892474547511297
Success
161: 668902994700836864
Success
162: 668932921458302977
Success
163: 668955713004314625
Success
164: 668960084974809088
Success
165: 668975677807423489
Success
166: 668979806671884288
Success
167: 668981893510119424
Success
168: 668986018524233728
Success
169: 668988183816871936
Success
170: 668989615043424256
Success
171: 668992363537309700
Success
172: 668994913074286592
Success
173: 669000397445533696
Success
174: 669006782128353280
Success
175: 669015743032369152
Success
176: 669037058363662336
Success
177: 669203728096960512
Success
178: 669214165781868544
Success
179: 669216679721873412
Success
180: 669324657376567296
Success
181: 669327207240699904
Success
182: 669328503091937280
Success
183: 669351434509529089
Success
184: 669353438988365824
Success
185: 669354382627049472
Success
186: 669359674819481600
Success
187: 669363888236994561
Success
188: 669367896104181761
Success
189: 669371483794317312
Success
190: 669375718304980992
Success
191: 669393256313184256
Success
192: 669564461267722241
Success
193: 669567591774625800
Success
194: 669571471778410496
Success
195: 669573570759163904
Success
196: 669583744538451968
Success
197: 669597912108789760
Success
198: 669603084620980224
Success
199: 669625907762618368
Success
200: 669661792646373376
Success
201: 669680153564442624
Success
202: 669682095984410625
Success
203: 669683899023405056
Success
204: 669749430875258880
Success
205: 669753178989142016
Success
206: 669923323644657664
Success
207: 669926384437997569
Success
208: 669942763794931712
Success
209: 669970042633789440
Success
210: 669972011175813120
Success
211: 669993076832759809
Success
212: 670003130994700288
Success
213: 670037189829525505
Success
214: 670040295598354432
Success
215: 670046952931721218
Success
216: 670055038660800512
Success
217: 670061506722140161
Success
218: 670069087419133954
Success
219: 670073503555706880
Success
220: 670079681849372674
Success
221: 670086499208155136
Success
222: 670093938074779648
Success
223: 670290420111441920
Success
224: 670303360680108032
Success
225: 670319130621435904
Success
226: 670338931251150849
Success
227: 670361874861563904
Success
228: 670374371102445568
Success
229: 670385711116361728
Success
230: 670403879788544000
Success
231: 670408998013820928
Success
232: 670411370698022913
Success
233: 670417414769758208
Success
234: 670420569653809152
Success
235: 670421925039075328
Success
236: 670427002554466305
Success
237: 670428280563085312
Success
238: 670433248821026816
Success
239: 670434127938719744
Success
240: 670435821946826752
Success
241: 670442337873600512
Success
242: 670444955656130560
Success
243: 670449342516494336
Success
244: 670452855871037440
Success
245: 670465786746662913
Success
246: 670468609693655041
Success
247: 670474236058800128
Success
248: 670668383499735048
Success
249: 670676092097810432
Success
250: 670679630144274432
Success
251: 670691627984359425
Success
252: 670704688707301377
Success
253: 670717338665226240
Success
254: 670727704916926465
Success
255: 670733412878163972
Success
256: 670755717859713024
Success
257: 670764103623966721
Success
258: 670778058496974848
Success
259: 670780561024270336
Success
260: 670782429121134593
Success
261: 670783437142401025

Success
262: 670786190031921152
Success
263: 670789397210615808
Success
264: 670792680469889025
Success
265: 670797304698376195
Success
266: 670803562457407488
Success
267: 670804601705242624
Success
268: 670807719151067136
Success
269: 670811965569282048
Success
270: 670815497391357952
Success
271: 670822709593571328
Success
272: 670823764196741120
Success
273: 670826280409919488
Success
274: 670832455012716544
Success
275: 670833812859932673
Success
276: 670838202509447168
Success
277: 670840546554966016
Success
278: 670842764863651840
Success
279: 670995969505435648
Success
280: 671109016219725825
Success
281: 671115716440031232
Success
282: 671122204919246848
Success
283: 671134062904504320
Success
284: 671138694582165504
Success
285: 671141549288370177
Success
286: 671147085991960577
Success
287: 671151324042559489
Success
288: 671154572044468225
Success
289: 671159727754231808
Success
290: 671163268581498880
Success
291: 671166507850801152
Success
292: 671182547775299584
Success
293: 671186162933985280
Success
294: 671347597085433856
Success
295: 671355857343524864
Success
296: 671357843010908160
Success
297: 671362598324076544
Success
298: 671390180817915904
Success
299: 671485057807351808
Success
300: 671486386088865792
Success
301: 671488513339211776
Success
302: 671497587707535361
Success
303: 671504605491109889
Success
304: 671511350426865664
Success
305: 671518598289059840
Success
306: 671520732782923777
Success
307: 671528761649688577
Success
308: 671533943490011136
Success
309: 671536543010570240
Success
310: 671538301157904385
Success
311: 671542985629241344
Success
312: 671544874165002241
Success
313: 671547767500775424
Success
314: 671561002136281088
Success
315: 671729906628341761
Success
316: 671735591348891648
Success
317: 671743150407421952
Success
318: 671744970634719232
Success
319: 671763349865160704
Success
320: 671768281401958400
Success
321: 671789708968640512
Success
322: 671855973984772097
Success
323: 671866342182637568
Success
324: 671874878652489728
Success
325: 671879137494245376
Success
326: 671882082306625538
Success
327: 671891728106971137
Success
328: 671896809300709376
Success
329: 672068090318987265
Success
330: 672082170312290304
Success
331: 672095186491711488
Success
332: 672125275208069120
Success
333: 672139350159835138
Success
334: 672160042234327040
Success
335: 672169685991993344
Success
336: 672205392827572224
Success
337: 672222792075620352
Success
338: 672231046314901505
Success
339: 672239279297454080
Success
340: 672245253877968896
Success
341: 672248013293752320
Success
342: 672254177670729728
Success
343: 672256522047614977
Success
344: 672264251789176834
Success
345: 672267570918129665
Success
346: 672272411274932228
Success
347: 672466075045466113
Success
348: 672475084225949696
Success
349: 672481316919734272
Success
350: 672482722825261057
Success
351: 672488522314567680
Success
352: 672523490734551040
Success
353: 672538107540070400
Success
354: 672591271085670400
Success
355: 672591762242805761
Success
356: 672594978741354496
Success
357: 672604026190569472
Success
358: 672609152938721280
Success
359: 672614745925664768
Success
360: 672622327801233409
Success
361: 672640509974827008
Success
362: 672828477930868736
Success
363: 672834301050937345
Success
364: 672877615439593473
Success
365: 672884426393653248
Success
366: 672898206762672129
Success
367: 672902681409806336
Success
368: 672964561327235073
Success
369: 672968025906282496
Success
370: 672970152493887488
Success
371: 672975131468300288
Success
372: 672980819271634944
Success
373: 672984142909456390
Success
374: 672988786805112832
Success
375: 672995267319328768
Success
376: 672997845381865473
Success
377: 673148804208660480
Success
378: 673213039743795200
Success
379: 673240798075449344
Success
380: 673270968295534593
Success
381: 673295268553605120
Success
382: 673317986296586240
Success
383: 673320132811366400
Success
384: 673342308415348736
Success
385: 673343217010679808
Success
386: 673345638550134785
Success
387: 673350198937153538
Success
388: 673352124999274496
Success
389: 673355879178194945
Success
390: 673359818736984064
Success
391: 673363615379013632
Success
392: 673576835670777856
Success
393: 673580926094458881
Success
394: 673583129559498752
Success
395: 673612854080196609
Success
396: 673636718965334016
Success
397: 673656262056419329
Success
398: 673662677122719744
Success
399: 673680198160809984
Success
400: 673686845050527744
Success
401: 673688752737402881
Success
402: 673689733134946305
Success
403: 673697980713705472
Success
404: 673700254269775872
Success
405: 673705679337693185
Success
406: 673707060090052608
Success
407: 673708611235921920
Success
408: 673709992831262724
Success
409: 673711475735838725
Success
410: 673715861853720576
Success
411: 673887867907739649
Success
412: 673906403526995968
Success
413: 673919437611909120
Success
414: 673956914389192708
Success
415: 674008982932058114
Success
416: 674014384960745472
Success
417: 674019345211760640
Success
418: 674024893172875264
Success
419: 674036086168010753
Success
420: 674038233588723717
Success
421: 674042553264685056
Success
422: 674045139690631169
Success
423: 674051556661161984
Success
424: 674053186244734976
Success
425: 674063288070742018
Success
426: 674075285688614912
Success
427: 674082852460433408
Success
428: 674255168825880576
Success
429: 674262580978937856
Success
430: 674265582246694913
Success
431: 674269164442398721
Success
432: 674271431610523648
Success
433: 674291837063053312
Success
434: 674318007229923329
Success
435: 674372068062928900
Success
436: 674394782723014656
Success
437: 674410619106390016
Success
438: 674416750885273600
Success
439: 674422304705744896
Success
440: 674436901579923456
Success
441: 674447403907457024
Success
442: 674468880899788800
Success
443: 674632714662858753
Success
444: 674638615994089473
Success
445: 674644256330530816
Success
446: 674646392044941312
Success
447: 674664755118911488
Success
448: 674670581682434048
Success
449: 674690135443775488
Success
450: 674737130913071104
Success
451: 674739953134403584
Success
452: 674743008475090944
Success
453: 674752233200820224
Success
454: 674754018082705410
Success
455: 674764817387900928
Success
456: 674767892831932416
Success
457: 674774481756377088
Success
458: 674781762103414784
Success
459: 674788554665512960
Success
460: 674790488185167872
Success
461: 674793399141146624
Success
462: 674800520222154752
Success
463: 674805413498527744
Success
464: 674999807681908736
Success
465: 675003128568291329
Success
466: 675006312288268288
Success
467: 675015141583413248
Success
468: 675047298674663426
Success
469: 675109292475830276
Success
470: 675111688094527488
Success
471: 675113801096802304
Success
472: 675135153782571009
Success
473: 675145476954566656
Success
474: 675146535592706048
Success
475: 675147105808306176
Success
476: 675149409102012420
Success
477: 675153376133427200
Success
478: 675166823650848770
Success
479: 675334060156301312
Success
480: 675349384339542016
Success
481: 675354435921575936
Success
482: 675362609739206656
Success
483: 675372240448454658
Success
484: 675432746517426176
Success
485: 675483430902214656
Success
486: 675489971617296384
Success
487: 675497103322386432
Success
488: 675501075957489664
Success
489: 675517828909424640
Success
490: 675522403582218240
Success
491: 675531475945709568
Success
492: 675534494439489536
Success
493: 675706639471788032
Success
494: 675707330206547968
Success
495: 675710890956750848
Success
496: 675740360753160193
Success
497: 675781562965868544
Success
498: 675798442703122432
Success
499: 675820929667219457
Success
500: 675822767435051008
Success
501: 675845657354215424
Success
502: 675853064436391936
Success
503: 675870721063669760
Success
504: 675878199931371520
Success
505: 675888385639251968
Success
506: 675891555769696257
Success
507: 675898130735476737
Success
508: 676089483918516224
Success
509: 676098748976615425
Success
510: 676101918813499392
Success
511: 676146341966438401
Success
512: 676191832485810177
Success
513: 676215927814406144
Success
514: 676219687039057920
Success
515: 676237365392908289
Success
516: 676263575653122048
Success
517: 676430933382295552
Success
518: 676440007570247681
Success
519: 676470639084101634

Success
520: 676496375194980353
Success
521: 676533798876651520
Success
522: 676575501977128964
Success
523: 676582956622721024
Success
524: 676588346097852417
Success
525: 676603393314578432
Success
526: 676606785097199616
Success
527: 676613908052996102
Success
528: 676617503762681856
Success
529: 676776431406465024
Success
530: 676811746707918848
Success
531: 676819651066732545
Success
532: 676821958043033607
Success
533: 676864501615042560
Success
534: 676897532954456065
Success
535: 676936541936185344
Success
536: 676942428000112642
Success
537: 676946864479084545
Success
538: 676948236477857792
Success
539: 676949632774234114
Success
540: 676957860086095872
Success
541: 676975532580409345
Success
542: 677187300187611136
Success
543: 677228873407442944
Success
544: 677269281705472000
Success
545: 677301033169788928
Success
546: 677314812125323265
Success
547: 677328882937298944
Success
548: 677331501395156992
Success
549: 677334615166730240
Success
550: 677530072887205888
Success
551: 677547928504967168
Success
552: 677557565589463040
Success
553: 677565715327688705
Success
554: 677573743309385728
Success
555: 677644091929329666
Success
556: 677662372920729601
Success
557: 677673981332312066
Success
558: 677687604918272002
Success
559: 677698403548192770
Success
560: 677700003327029250
Success
561: 677716515794329600
Success
562: 677895101218201600
Success
563: 677918531514703872
Success
564: 678021115718029313
Success
565: 678255464182861824
Success
566: 678278586130948096
Success
567: 678334497360859136
Success
568: 678341075375947776
Success
569: 678380236862578688
Success
570: 678389028614488064
Success
571: 678396796259975168
Success
572: 678399652199309312
Success
573: 678410210315247616
Success
574: 678424312106393600
Success
575: 678446151570427904
Success
576: 678643457146150913
Success
577: 678675843183484930
Success
578: 678740035362037760
Success
579: 678755239630127104
Success
580: 678764513869611008
Success
581: 678767140346941444
Success
582: 678774928607469569
Success
583: 678798276842360832
Success
584: 678800283649069056
Success
585: 678969228704284672
Success
586: 678991772295516161
Success
587: 679047485189439488
Success
588: 679062614270468097
Success
589: 679111216690831360
Success
590: 679132435750195208
Success
591: 679148763231985668
Success
592: 679158373988876288
Success
593: 679462823135686656
Success
594: 679475951516934144
Success
595: 679503373272485890
Success
596: 679511351870550016
Success
597: 679527802031484928
Success
598: 679530280114372609
Success
599: 679722016581222400
Success
600: 679729593985699840
Success
601: 679736210798047232
Success
602: 679777920601223168
Success
603: 679828447187857408
Success
604: 679844490799091713
Success
605: 679854723806179328
Success
606: 679862121895714818
Success
607: 679877062409191424
Success
608: 680055455951884288
Fail
609: 680070545539371008
Success
610: 680085611152338944
Success
611: 680100725817409536
Success
612: 680115823365742593
Success
613: 680130881361686529
Success
614: 680145970311643136
Success
615: 680161097740095489
Success
616: 680176173301628928
Success
617: 680191257256136705
Success
618: 680206703334408192
Success
619: 680221482581123072
Success
620: 680440374763077632
Success
621: 680473011644985345
Success
622: 680494726643068929
Success
623: 680497766108381184
Success
624: 680583894916304897
Success
625: 680609293079592961
Success
626: 680798457301471234
Success
627: 680801747103793152
Success
628: 680836378243002368
Success
629: 680889648562991104
Success
630: 680913438424612864
Success
631: 680934982542561280
Success
632: 680940246314430465
Success
633: 680959110691590145
Success
634: 680970795137544192
Success
635: 681193455364796417
Success
636: 681231109724700672
Success
637: 681242418453299201
Success
638: 681261549936340994
Success
639: 681281657291280384
Success
640: 681297372102656000
Success
641: 681302363064414209
Success
642: 681320187870711809
Success
643: 681339448655802368
Success
644: 681523177663676416
Success
645: 681579835668455424
Success
646: 681610798867845120
Success
647: 681654059175129088
Success
648: 681679526984871937
Success
649: 681694085539872773
Success
650: 681891461017812993
Success
651: 681981167097122816
Success
652: 682003177596559360
Success
653: 682032003584274432
Success
654: 682047327939461121
Success
655: 682059653698686977
Success
656: 682242692827447297
Success
657: 682259524040966145
Success
658: 682303737705140231
Success
659: 682389078323662849
Success
660: 682393905736888321
Success
661: 682406705142087680
Success
662: 682429480204398592
Success
663: 682638830361513985
Success
664: 682662431982772225
Success
665: 682697186228989953
Success
666: 682750546109968385
Success
667: 682788441537560576
Success
668: 682962037429899265
Success
669: 683030066213818368
Success
670: 683078886620553216
Success
671: 683098815881154561
Success
672: 683111407806746624
Success
673: 683142553609318400
Success
674: 683357973142474752
Success
675: 683391852557561860
Success
676: 683449695444799489
Success
677: 683462770029932544
Success
678: 683481228088049664
Success
679: 683498322573824003
Success
680: 683742671509258241
Success
681: 683773439333797890
Success
682: 683828599284170753
Success
683: 683834909291606017
Success
684: 683849932751646720
Success
685: 683852578183077888
Success
686: 683857920510050305
Success
687: 684097758874210310
Success
688: 684122891630342144
Success
689: 684177701129875456
Success
690: 684188786104872960
Success
691: 684195085588783105
Success
692: 684200372118904832
Success
693: 684222868335505415
Success
694: 684225744407494656
Success
695: 684241637099323392
Success
696: 684460069371654144
Success
697: 684481074559381504
Success
698: 684538444857667585
Success
699: 684567543613382656
Success
700: 684594889858887680
Success
701: 684800227459624960
Success
702: 684880619965411328
Success
703: 684902183876321280
Success
704: 684914660081053696
Success
705: 684926975086034944
Success
706: 684940049151070208
Success
707: 684959798585110529
Success
708: 685169283572338688
Success
709: 685198997565345792
Success
710: 685268753634967552
Success
711: 685307451701334016
Success
712: 685315239903100929
Success
713: 685321586178670592
Success
714: 685325112850124800
Success
715: 685532292383666176
Success
716: 685547936038666240
Success
717: 685641971164143616
Success
718: 685663452032069632
Success
719: 685667379192414208
Success
720: 685906723014619143
Success
721: 685943807276412928
Success
722: 685973236358713344
Success
723: 686003207160610816
Success
724: 686007916130873345
Success
725: 686034024800862208
Success
726: 686050296934563840
Success
727: 686358356425093120
Success
728: 686377065986265092
Success
729: 686386521809772549
Success
730: 686606069955735556
Success
731: 686618349602762752
Success
732: 686683045143953408
Success
733: 686730991906516992
Success
734: 686749460672679938
Success
735: 686947101016735744
Success
736: 687096057537363968
Success
737: 687102708889812993
Success
738: 687109925361856513
Success
739: 687124485711986689
Success
740: 687127927494963200
Success
741: 687312378585812992
Success
742: 687317306314240000
Success
743: 687460506001633280
Success
744: 687476254459715584
Success
745: 687480748861947905
Success
746: 687494652870668288
Success
747: 687664829264453632
Success
748: 687704180304273409
Success
749: 687807801670897665
Success
750: 687818504314159109
Success
751: 687826841265172480
Success
752: 688064179421470721
Success
753: 688116655151435777
Success
754: 688179443353796608
Success
755: 688211956440801280
Success
756: 688385280030670848
Success
757: 688519176466644993
Success
758: 688547210804498433
Success
759: 688789766343622656
Success
760: 688804835492233216
Success
761: 688828561667567616
Success
762: 688894073864884227
Success
763: 688898160958271489
Success
764: 688908934925697024
Success
765: 688916208532455424
Success
766: 689143371370250240
Success
767: 689154315265683456
Success
768: 689275259254616065
Success
769: 689280876073582592
Success
770: 689283819090870273
Success
771: 689289219123089408
Success
772: 689517482558820352
Success
773: 689557536375177216
Success
774: 689599056876867584
Success
775: 689623661272240129
Success
776: 689659372465688576
Success
777: 689661964914655233

Success
778: 689835978131935233
Success
779: 689877686181715968
Success
780: 689905486972461056
Success
781: 689977555533848577
Success
782: 689999384604450816
Success
783: 690005060500217858
Success
784: 690015576308211712
Success
785: 690021994562220032
Success
786: 690248561355657216
Success
787: 690360449368465409
Success
788: 690374419777196032
Success
789: 690400367696297985
Success
790: 690597161306841088
Success
791: 690649993829576704
Success
792: 690690673629138944
Success
793: 690728923253055490
Success
794: 690735892932222976
Success
795: 690932576555528194
Success
796: 690938899477221376
Success
797: 690959652130045952
Success
798: 691090071332753408
Success
799: 691096613310316544
Success
800: 691321916024623104
Success
801: 691416866452082688
Success
802: 691444869282295808
Success
803: 691459709405118465
Success
804: 691483041324204033
Success
805: 691675652215414786
Success
806: 691756958957883396
Success
807: 691820333922455552
Success
808: 692017291282812928
Success
809: 692142790915014657
Success
810: 692158366030913536
Success
811: 692187005137076224
Success
812: 692417313023332352
Success
813: 692530551048294401
Success
814: 692535307825213440
Success
815: 692568918515392513
Success
816: 692752401762250755
Success
817: 692828166163931137
Success
818: 692894228850999298
Success
819: 692901601640583168
Success
820: 692905862751522816
Success
821: 692919143163629568
Success
822: 693095443459342336
Success
823: 693109034023534592
Success
824: 693155686491000832
Success
825: 693231807727280129
Success
826: 693262851218264065
Success
827: 693280720173801472
Success
828: 693486665285931008
Success
829: 693590843962331137
Success
830: 693622659251335168
Success
831: 693629975228977152
Success
832: 693642232151285760
Success
833: 693647888581312512
Success
834: 693942351086120961
Success
835: 694001791655137281
Success
836: 694183373896572928
Success
837: 694206574471057408
Success
838: 694329668942569472
Success
839: 694352839993344000
Success
840: 694356675654983680
Success
841: 694669722378485760
Success
842: 694905863685980160
Success
843: 695051054296211456
Success
844: 695064344191721472
Success
845: 695074328191332352
Success
846: 695095422348574720
Success
847: 695314793360662529
Success
848: 695409464418041856
Success
849: 695446424020918272
Success
850: 695629776980148225
Success
851: 695767669421768709
Success
852: 695794761660297217
Success
853: 695816827381944320
Success
854: 696405997980676096
Success
855: 696488710901260288
Success
856: 696713835009417216
Success
857: 696754882863349760
Success
858: 696877980375769088
Success
859: 696886256886657024
Success
860: 696894894812565505
Success
861: 696900204696625153
Success
862: 697242256848379904
Success
863: 697255105972801536
Success
864: 697259378236399616
Success
865: 697270446429966336
Success
866: 697463031882764288
Success
867: 697482927769255936
Success
868: 697575480820686848
Success
869: 697596423848730625
Success
870: 697616773278015490
Success
871: 697881462549430272
Success
872: 697943111201378304
Success
873: 697990423684476929
Success
874: 697995514407682048
Success
875: 698178924120031232
Success
876: 698195409219559425
Success
877: 698262614669991936
Success
878: 698342080612007937
Success
879: 698355670425473025
Success
880: 698549713696649216
Success
881: 698635131305795584
Success
882: 698703483621523456
Success
883: 698710712454139905
Success
884: 698907974262222848
Success
885: 698953797952008193
Success
886: 698989035503689728
Success
887: 699036661657767936
Success
888: 699072405256409088
Success
889: 699079609774645248
Success
890: 699088579889332224
Success
891: 699323444782047232
Success
892: 699370870310113280
Success
893: 699413908797464576
Success
894: 699423671849451520
Success
895: 699434518667751424
Success
896: 699446877801091073
Success
897: 699691744225525762
Success
898: 699775878809702401
Success
899: 699779630832685056
Success
900: 699788877217865730
Success

Rate limit reached. Sleeping for: 742

901: 699801817392291840
Success
902: 700002074055016451
Success
903: 700029284593901568
Success
904: 700062718104104960
Success
905: 700143752053182464
Success
906: 700151421916807169
Success
907: 700167517596164096
Success
908: 700462010979500032
Success
909: 700505138482569216
Success
910: 700518061187723268
Success
911: 700747788515020802
Success
912: 700796979434098688
Success
913: 700847567345688576
Success
914: 700864154249383937
Success
915: 700890391244103680
Success
916: 701214700881756160
Success
917: 701545186879471618
Success
918: 701570477911896070
Success
919: 701601587219795968
Success
920: 701889187134500865
Success
921: 701952816642965504
Success
922: 701981390485725185
Success
923: 702217446468493312
Success
924: 702276748847800320
Success
925: 702321140488925184
Success
926: 702539513671897089
Success
927: 702598099714314240
Success
928: 702671118226825216
Success
929: 702684942141153280
Success
930: 702932127499816960
Success
931: 703041949650034688
Success
932: 703079050210877440
Success
933: 703268521220972544
Success
934: 703356393781329922
Success
935: 703382836347330562
Success
936: 703407252292673536
Success
937: 703425003149250560
Success
938: 703611486317502464
Success
939: 703631701117943808
Success
940: 703769065844768768
Success
941: 703774238772166656
Success
942: 704054845121142784
Success
943: 704113298707505153
Success
944: 704347321748819968
Success
945: 704364645503647744
Success
946: 704480331685040129
Success
947: 704499785726889984
Success
948: 704761120771465216
Success
949: 704819833553219584
Success
950: 704847917308362754
Success
951: 704859558691414016
Success
952: 704871453724954624
Success
953: 705066031337840642
Success
954: 705102439679201280
Success
955: 705223444686888960
Success
956: 705239209544720384
Success
957: 705428427625635840
Success
958: 705442520700944385
Success
959: 705475953783398401
Success
960: 705591895322394625
Success
961: 705786532653883392
Success
962: 705898680587526145
Success
963: 705970349788291072
Success
964: 705975130514706432
Success
965: 706166467411222528
Success
966: 706265994973601792
Success
967: 706291001778950144
Success
968: 706310011488698368
Success
969: 706346369204748288
Success
970: 706516534877929472
Success
971: 706538006853918722
Success
972: 706593038911545345
Success
973: 706644897839910912
Success
974: 706681918348251136
Success
975: 706901761596989440
Success
976: 707014260413456384
Success
977: 707021089608753152
Success
978: 707038192327901184
Success
979: 707059547140169728
Success
980: 707297311098011648
Success
981: 707315916783140866
Success
982: 707377100785885184
Success
983: 707387676719185920
Success
984: 707411934438625280
Success
985: 707420581654872064
Success
986: 707610948723478529
Success
987: 707693576495472641
Success
988: 707741517457260545
Success
989: 707776935007539200
Success
990: 707969809498152960
Success
991: 707995814724026368
Success
992: 708026248782585858
Success
993: 708109389455101952
Success
994: 708119489313951744
Success
995: 708130923141795840
Success
996: 708149363256774660
Success
997: 708349470027751425
Success
998: 708356463048204288
Success
999: 708469915515297792
Success
1000: 708479650088034305
Success
1001: 708711088997666817
Success
1002: 708738143638450176
Success
1003: 708810915978854401
Success
1004: 708834316713893888
Success
1005: 708845821941387268
Success
1006: 709042156699303936
Success
1007: 709158332880297985
Success
1008: 709198395643068416
Success
1009: 709207347839836162
Success
1010: 709225125749587968
Success
1011: 709409458133323776
Success
1012: 709449600415961088
Success
1013: 709519240576036864
Success
1014: 709556954897764353
Success
1015: 709566166965075968
Success
1016: 709852847387627521
Success
1017: 709901256215666688
Success
1018: 709918798883774466
Success
1019: 710117014656950272
Success
1020: 710140971284037632
Success
1021: 710153181850935296
Success
1022: 710269109699739648
Success
1023: 710272297844797440
Success
1024: 710283270106132480
Success
1025: 710588934686908417
Success
1026: 710658690886586372
Success
1027: 710833117892898816
Success
1028: 710844581445812225
Success
1029: 710997087345876993
Success
1030: 711008018775851008
Success
1031: 711306686208872448
Success
1032: 711363825979756544
Success
1033: 711652651650457602
Success
1034: 711694788429553666
Success
1035: 711732680602345472
Success
1036: 711743778164514816
Success
1037: 711968124745228288
Success
1038: 711998809858043904
Success
1039: 712065007010385924
Success
1040: 712085617388212225
Success
1041: 712092745624633345
Success
1042: 712097430750289920
Success
1043: 712438159032893441
Success
1044: 712668654853337088
Success
1045: 712717840512598017
Success
1046: 712809025985978368
Success
1047: 713175907180089344
Success
1048: 713177543487135744
Success
1049: 713411074226274305
Success
1050: 713761197720473600
Success
1051: 713900603437621249
Success
1052: 713919462244790272
Success
1053: 714141408463036416
Success
1054: 714214115368108032
Success
1055: 714251586676113411
Success
1056: 714258258790387713
Success
1057: 714606013974974464
Success
1058: 714631576617938945
Success
1059: 714957620017307648
Success
1060: 714982300363173890
Success
1061: 715009755312439296
Success
1062: 715200624753819648
Success
1063: 715220193576927233
Success
1064: 715342466308784130
Success
1065: 715360349751484417
Success
1066: 715680795826982913
Success
1067: 715696743237730304
Success
1068: 715733265223708672
Success
1069: 715928423106027520
Success
1070: 716080869887381504
Success
1071: 716285507865542656
Success
1072: 716439118184652801
Success
1073: 716791146589110272
Success
1074: 716802964044845056
Success
1075: 717009362452090881
Success
1076: 717047459982213120
Success
1077: 717421804990701568
Success
1078: 717537687239008257
Success
1079: 717790033953034240
Success
1080: 717841801130979328
Success
1081: 718234618122661888
Success
1082: 718246886998687744
Success
1083: 718454725339934721
Success
1084: 718460005985447936
Success
1085: 718540630683709445
Success
1086: 718613305783398402
Success
1087: 718631497683582976
Success
1088: 718939241951195136
Success
1089: 718971898235854848
Success
1090: 719332531645071360
Success
1091: 719339463458033665
Success
1092: 719367763014393856
Success
1093: 719551379208073216
Success
1094: 719704490224398336
Success
1095: 719991154352222208
Success
1096: 720043174954147842
Success
1097: 720059472081784833
Success
1098: 720340705894408192
Success
1099: 720389942216527872
Success
1100: 720415127506415616
Success
1101: 720775346191278080
Success
1102: 720785406564900865
Success
1103: 721001180231503872
Success
1104: 721503162398597120
Success
1105: 722613351520608256
Success
1106: 722974582966214656
Success
1107: 723179728551723008
Success
1108: 723673163800948736
Success
1109: 723688335806480385
Success
1110: 723912936180330496
Success
1111: 724004602748780546
Success
1112: 724046343203856385
Success
1113: 724049859469295616
Success
1114: 724405726123311104
Success
1115: 724771698126512129
Success
1116: 724983749226668032
Success
1117: 725729321944506368
Success
1118: 725786712245440512
Success
1119: 725842289046749185
Success
1120: 726224900189511680
Success
1121: 726828223124897792
Success
1122: 726887082820554753
Success
1123: 726935089318363137
Success
1124: 727175381690781696
Success
1125: 727286334147182592
Success
1126: 727314416056803329
Success
1127: 727524757080539137
Success
1128: 727644517743104000
Success
1129: 727685679342333952
Success
1130: 728015554473250816
Success
1131: 728035342121635841
Success
1132: 728046963732717569
Success
1133: 728387165835677696
Success
1134: 728409960103686147
Success
1135: 728653952833728512
Success
1136: 728751179681943552
Success
1137: 728760639972315136
Success
1138: 728986383096946689
Success
1139: 729113531270991872
Success
1140: 729463711119904772
Success
1141: 729823566028484608
Success
1142: 729838605770891264
Success
1143: 729854734790754305
Success
1144: 730196704625098752
Success
1145: 730211855403241472
Success
1146: 730427201120833536
Success
1147: 730573383004487680
Success
1148: 730924654643314689
Success
1149: 731156023742988288
Success
1150: 731285275100512256
Success
1151: 732005617171337216
Success
1152: 732375214819057664

Success
1153: 732585889486888962
Success
1154: 732726085725589504
Success
1155: 732732193018155009
Success
1156: 733109485275860992
Success
1157: 733460102733135873
Success
1158: 733482008106668032
Success
1159: 733822306246479872
Success
1160: 733828123016450049
Success
1161: 734776360183431168
Success
1162: 734787690684657664
Success
1163: 734912297295085568
Success
1164: 735137028879360001
Success
1165: 735256018284875776
Success
1166: 735274964362878976
Success
1167: 735635087207878657
Success
1168: 735648611367784448
Success
1169: 735991953473572864
Success
1170: 736010884653420544
Success
1171: 736225175608430592
Success
1172: 736365877722001409
Success
1173: 736736130620620800
Success
1174: 737310737551491075
Success
1175: 737322739594330112
Success
1176: 737445876994609152
Success
1177: 737678689543020544
Success
1178: 737800304142471168
Success
1179: 737826014890496000
Success
1180: 738156290900254721
Success
1181: 738166403467907072
Success
1182: 738184450748633089
Success
1183: 738402415918125056
Success
1184: 738537504001953792
Success
1185: 738883359779196928
Success
1186: 738885046782832640
Success
1187: 739238157791694849
Success
1188: 739485634323156992
Success
1189: 739544079319588864
Success
1190: 739606147276148736
Success
1191: 739844404073074688
Success
1192: 739932936087216128
Success
1193: 739979191639244800
Success
1194: 740214038584557568
Success
1195: 740359016048689152
Success
1196: 740365076218183684
Success
1197: 740373189193256964
Success
1198: 740676976021798912
Success
1199: 740699697422163968
Success
1200: 740711788199743490
Success
1201: 740995100998766593
Success
1202: 741067306818797568
Success
1203: 741303864243200000
Success
1204: 741438259667034112
Success
1205: 741743634094141440
Success
1206: 741793263812808706
Success
1207: 742150209887731712
Success
1208: 742161199639494656
Success
1209: 742385895052087300
Success
1210: 742423170473463808
Success
1211: 742465774154047488
Success
1212: 742528092657332225
Success
1213: 743210557239623680
Success
1214: 743222593470234624
Success
1215: 743253157753532416
Success
1216: 743510151680958465
Success
1217: 743545585370791937
Success
1218: 743595368194129920
Success
1219: 743609206067040256
Success
1220: 743895849529389061
Success
1221: 743980027717509120
Success
1222: 744234799360020481
Success
1223: 744334592493166593
Success
1224: 744709971296780288
Success
1225: 744971049620602880
Success
1226: 744995568523612160
Success
1227: 745057283344719872
Success
1228: 745314880350101504
Success
1229: 745422732645535745
Success
1230: 745433870967832576
Success
1231: 745712589599014916
Success
1232: 745789745784041472
Success
1233: 746056683365994496
Success
1234: 746131877086527488
Success
1235: 746369468511756288
Success
1236: 746507379341139972
Success
1237: 746726898085036033
Success
1238: 746790600704425984
Success
1239: 746818907684614144
Success
1240: 746872823977771008
Success
1241: 746906459439529985
Success
1242: 747103485104099331
Success
1243: 747204161125646336
Success
1244: 747219827526344708
Success
1245: 747461612269887489
Success
1246: 747512671126323200
Success
1247: 747594051852075008
Success
1248: 747600769478692864
Success
1249: 747816857231626240
Success
1250: 747844099428986880
Success
1251: 747885874273214464
Success
1252: 747933425676525569
Success
1253: 747963614829678593
Success
1254: 748307329658011649
Success
1255: 748324050481647620
Success
1256: 748346686624440324
Success
1257: 748568946752774144
Success
1258: 748575535303884801
Success
1259: 748692773788876800
Success
1260: 748699167502000129
Success
1261: 748705597323898880
Success
1262: 748932637671223296
Success
1263: 748977405889503236
Success
1264: 749036806121881602
Success
1265: 749064354620928000
Success
1266: 749317047558017024
Success
1267: 749395845976588288
Success
1268: 749403093750648834
Success
1269: 749417653287129088
Success
1270: 749774190421639168
Success
1271: 749981277374128128
Success
1272: 749996283729883136
Success
1273: 750011400160841729
Success
1274: 750026558547456000
Success
1275: 750041628174217216
Success
1276: 750056684286914561
Success
1277: 750071704093859840
Success
1278: 750086836815486976
Success
1279: 750101899009982464
Success
1280: 750117059602808832
Success
1281: 750132105863102464
Success
1282: 750147208377409536
Success
1283: 750383411068534784
Success
1284: 750429297815552001
Success
1285: 750506206503038976
Success
1286: 750719632563142656
Success
1287: 750868782890057730
Success
1288: 751132876104687617
Success
1289: 751205363882532864
Success
1290: 751251247299190784
Success
1291: 751456908746354688
Success
1292: 751538714308972544
Success
1293: 751583847268179968
Success
1294: 751598357617971201
Success
1295: 751830394383790080
Success
1296: 751937170840121344
Success
1297: 752173152931807232
Success
1298: 752309394570878976
Success
1299: 752334515931054080
Success
1300: 752519690950500352
Success
1301: 752660715232722944
Success
1302: 752682090207055872
Success
1303: 752917284578922496
Success
1304: 753026973505581056
Success
1305: 753294487569522689
Success
1306: 753375668877008896
Success
1307: 753398408988139520
Success
1308: 753420520834629632
Success
1309: 753655901052166144
Success
1310: 754011816964026368
Fail
1311: 754120377874386944
Success
1312: 754449512966619136
Success
1313: 754482103782404096
Success
1314: 754747087846248448
Success
1315: 754856583969079297
Success
1316: 754874841593970688
Success
1317: 755110668769038337
Success
1318: 755206590534418437
Success
1319: 755955933503782912
Success
1320: 756275833623502848
Success
1321: 756288534030475264
Success
1322: 756303284449767430
Success
1323: 756526248105566208
Success
1324: 756651752796094464
Success
1325: 756939218950160384
Success
1326: 756998049151549440
Success
1327: 757354760399941633
Success
1328: 757393109802180609
Success
1329: 757400162377592832
Success
1330: 757596066325864448
Success
1331: 757597904299253760
Success
1332: 757611664640446465
Success
1333: 757725642876129280
Success
1334: 757729163776290825
Success
1335: 757741869644341248
Success
1336: 758041019896193024
Success
1337: 758355060040593408
Success
1338: 758405701903519748
Success
1339: 758467244762497024
Success
1340: 758474966123810816
Success
1341: 758740312047005698
Success
1342: 758828659922702336
Success
1343: 758854675097526272
Success
1344: 759047813560868866
Success
1345: 759099523532779520
Success
1346: 759159934323924993
Success
1347: 759197388317847553
Success
1348: 759447681597108224
Success
1349: 759557299618865152
Success
1350: 759566828574212096
Fail
1351: 759793422261743616
Success
1352: 759846353224826880
Success
1353: 759923798737051648
Success
1354: 760190180481531904
Success
1355: 760252756032651264
Success
1356: 760290219849637889
Success
1357: 760539183865880579
Success
1358: 760641137271070720
Success
1359: 760656994973933572
Success
1360: 760893934457552897
Success
1361: 761004547850530816
Success
1362: 761227390836215808
Success
1363: 761292947749015552
Success
1364: 761334018830917632
Success
1365: 761371037149827077
Success
1366: 761599872357261312
Success
1367: 761672994376806400
Success
1368: 761745352076779520
Success
1369: 761750502866649088
Success
1370: 761976711479193600
Success
1371: 762035686371364864
Success
1372: 762316489655476224
Success
1373: 762464539388485633
Success
1374: 762471784394268675
Success
1375: 762699858130116608
Success
1376: 763103485927849985
Success
1377: 763183847194451968
Success
1378: 763837565564780549
Success
1379: 764259802650378240
Success
1380: 764857477905154048
Success
1381: 765222098633691136
Success
1382: 765371061932261376
Success
1383: 765395769549590528
Success
1384: 765669560888528897
Success
1385: 765719909049503744
Success
1386: 766008592277377025
Success
1387: 766069199026450432
Success
1388: 766078092750233600
Success
1389: 766313316352462849
Success
1390: 766423258543644672
Success
1391: 766693177336135680
Success
1392: 766793450729734144
Success
1393: 767122157629476866
Success
1394: 767191397493538821
Success
1395: 767500508068192258
Success
1396: 767754930266464257
Success
1397: 767884188863397888
Success
1398: 768193404517830656
Success
1399: 768473857036525572
Success
1400: 768596291618299904
Success

1401: 768609597686943744
Success
1402: 768855141948723200
Success
1403: 768970937022709760
Success
1404: 769212283578875904
Success
1405: 769695466921623552
Success
1406: 769940425801170949
Success
1407: 770069151037685760
Success
1408: 770093767776997377
Success
1409: 770293558247038976
Success
1410: 770414278348247044
Success
1411: 770655142660169732
Success
1412: 770772759874076672
Success
1413: 770787852854652928
Success
1414: 771004394259247104
Fail
1415: 771014301343748096
Success
1416: 771102124360998913
Success
1417: 771136648247640064
Success
1418: 771171053431250945
Success
1419: 771380798096281600
Success
1420: 771500966810099713
Success
1421: 771770456517009408
Success
1422: 772102971039580160
Success
1423: 772114945936949249
Success
1424: 772117678702071809
Success
1425: 772152991789019136
Success
1426: 772193107915964416
Success
1427: 772581559778025472
Success
1428: 772615324260794368
Success
1429: 772826264096874500
Success
1430: 772877495989305348
Success
1431: 773191612633579521
Success
1432: 773247561583001600
Success
1433: 773308824254029826
Success
1434: 773547596996571136
Success
1435: 773670353721753600
Success
1436: 773704687002451968
Success
1437: 773922284943896577
Success
1438: 773985732834758656
Success
1439: 774314403806253056
Success
1440: 774639387460112384
Success
1441: 774757898236878852
Success
1442: 775085132600442880
Success
1443: 775364825476165632
Success
1444: 775729183532220416
Success
1445: 775733305207554048
Success
1446: 775842724423557120
Success
1447: 775898661951791106
Success
1448: 776088319444877312
Success
1449: 776113305656188928
Success
1450: 776201521193218049
Success
1451: 776218204058357768
Success
1452: 776477788987613185
Success
1453: 776813020089548800
Success
1454: 776819012571455488
Success
1455: 777189768882946048
Success
1456: 777621514455814149
Success
1457: 777641927919427584
Success
1458: 777684233540206592
Success
1459: 777885040357281792
Success
1460: 778027034220126208
Success
1461: 778039087836069888
Success
1462: 778286810187399168
Success
1463: 778383385161035776
Success
1464: 778396591732486144
Success
1465: 778408200802557953
Success
1466: 778624900596654080
Success
1467: 778650543019483137
Success
1468: 778748913645780993
Success
1469: 778990705243029504
Success
1470: 779056095788752897
Success
1471: 779123168116150273
Fail
1472: 779377524342161408
Success
1473: 779834332596887552
Success
1474: 780192070812196864
Success
1475: 780459368902959104
Success
1476: 780476555013349377
Success
1477: 780496263422808064
Success
1478: 780543529827336192
Success
1479: 780601303617732608
Success
1480: 780800785462489090
Success
1481: 780858289093574656
Success
1482: 780931614150983680
Success
1483: 781163403222056960
Success
1484: 781251288990355457
Success
1485: 781524693396357120
Success
1486: 781661882474196992
Success
1487: 781955203444699136
Success
1488: 782021823840026624
Success
1489: 782305867769217024
Success
1490: 782598640137187329
Success
1491: 782722598790725632
Success
1492: 782747134529531904
Success
1493: 782969140009107456
Success
1494: 783085703974514689
Success
1495: 783334639985389568
Success
1496: 783347506784731136
Success
1497: 783391753726550016
Success
1498: 783466772167098368
Success
1499: 783695101801398276
Success
1500: 783821107061198850
Success
1501: 783839966405230592
Success
1502: 784431430411685888
Success
1503: 784517518371221505
Success
1504: 784826020293709826
Success
1505: 785170936622350336
Success
1506: 785264754247995392
Success
1507: 785533386513321988
Success
1508: 785639753186217984
Success
1509: 785872687017132033
Success
1510: 785927819176054784
Success
1511: 786036967502913536
Success
1512: 786233965241827333
Success
1513: 786363235746385920
Success
1514: 786595970293370880
Success
1515: 786664955043049472
Success
1516: 786709082849828864
Success
1517: 786963064373534720
Success
1518: 787322443945877504
Success
1519: 787397959788929025
Success
1520: 787717603741622272
Success
1521: 787810552592695296
Success
1522: 788039637453406209
Success
1523: 788070120937619456
Success
1524: 788150585577050112
Success
1525: 788178268662984705
Success
1526: 788412144018661376
Success
1527: 788765914992902144
Success
1528: 788908386943430656
Success
1529: 789137962068021249
Success
1530: 789268448748703744
Success
1531: 789530877013393408
Success
1532: 789599242079838210
Success
1533: 789628658055020548
Success
1534: 789986466051088384
Success
1535: 790277117346975746
Success
1536: 790337589677002753
Success
1537: 790581949425475584
Success
1538: 790698755171364864
Success
1539: 790723298204217344
Success
1540: 790946055508652032
Success
1541: 790987426131050500
Success
1542: 791026214425268224
Success
1543: 791312159183634433
Success
1544: 791406955684368384
Success
1545: 791672322847637504
Success
1546: 792050063153438720
Success
1547: 792394556390137856
Success
1548: 792773781206999040
Success
1549: 792883833364439040
Success
1550: 792913359805018113
Success
1551: 793120401413079041
Success
1552: 793135492858580992
Success
1553: 793150605191548928
Success
1554: 793165685325201412
Success
1555: 793180763617361921
Success
1556: 793195938047070209
Success
1557: 793210959003287553
Success
1558: 793226087023144960
Success
1559: 793241302385262592
Success
1560: 793256262322548741
Success
1561: 793271401113350145
Success
1562: 793286476301799424
Success
1563: 793500921481273345
Success
1564: 793601777308463104
Success
1565: 793614319594401792
Success
1566: 793845145112371200
Success
1567: 793962221541933056
Success
1568: 794205286408003585
Success
1569: 794332329137291264
Success
1570: 794355576146903043
Success
1571: 794926597468000259
Success
1572: 794983741416415232
Success
1573: 795076730285391872
Success
1574: 795400264262053889
Success
1575: 795464331001561088
Success
1576: 796031486298386433
Success
1577: 796080075804475393
Success
1578: 796116448414461957
Success
1579: 796149749086875649
Success
1580: 796177847564038144
Success
1581: 796387464403357696
Success
1582: 796484825502875648
Success
1583: 796759840936919040
Success
1584: 796865951799083009
Success
1585: 797236660651966464
Success
1586: 797545162159308800
Success
1587: 797971864723324932
Success
1588: 798209839306514432
Success
1589: 798340744599797760
Success
1590: 798628517273620480
Success
1591: 798644042770751489
Success
1592: 798665375516884993
Success
1593: 798673117451325440
Success
1594: 798694562394996736
Success
1595: 798697898615730177
Success
1596: 798925684722855936
Success
1597: 798933969379225600
Success
1598: 799063482566066176
Success
1599: 799297110730567681
Success
1600: 799422933579902976
Success
1601: 799757965289017345
Success
1602: 799774291445383169
Success
1603: 800018252395122689
Success
1604: 800141422401830912
Success
1605: 800388270626521089
Success
1606: 800443802682937345
Success
1607: 800459316964663297
Success
1608: 800513324630806528
Success
1609: 800751577355128832
Success
1610: 801115127852503040
Success
1611: 801167903437357056
Success
1612: 801285448605831168
Success
1613: 801538201127157760
Success
1614: 801958328846974976
Success
1615: 802239329049477120
Success
1616: 802247111496568832
Fail
1617: 802265048156610565
Success
1618: 802323869084381190
Success
1619: 802572683846291456
Success
1620: 802624713319034886
Success
1621: 802952499103731712
Success
1622: 803276597545603072
Success
1623: 803380650405482500
Success
1624: 803638050916102144
Success
1625: 803692223237865472
Success
1626: 803773340896923648
Success
1627: 804026241225523202
Success
1628: 804413760345620481
Success
1629: 804738756058218496
Success
1630: 805207613751304193
Success
1631: 805487436403003392
Success
1632: 805520635690676224
Success
1633: 805826884734976000
Success
1634: 805932879469572096
Success
1635: 805958939288408065
Success
1636: 806219024703037440
Success
1637: 806242860592926720
Success
1638: 806542213899489280
Success
1639: 806629075125202948
Success
1640: 807010152071229440
Success
1641: 807059379405148160
Success
1642: 807106840509214720
Success
1643: 807621403335917568
Success
1644: 808001312164028416
Success
1645: 808106460588765185
Success
1646: 808134635716833280
Success
1647: 808501579447930884
Success
1648: 808733504066486276
Success
1649: 808838249661788160

Success
1650: 809084759137812480
Success
1651: 809220051211603969
Success
1652: 809448704142938112
Success
1653: 809808892968534016
Success
1654: 809920764300447744
Success
1655: 810254108431155201
Success
1656: 810284430598270976
Success
1657: 810657578271330305
Success
1658: 810896069567610880
Success
1659: 810984652412424192
Success
1660: 811386762094317568
Success
1661: 811627233043480576
Success
1662: 811744202451197953
Success
1663: 811985624773361665
Success
1664: 812372279581671427
Success
1665: 812466873996607488
Success
1666: 812503143955202048
Success
1667: 812709060537683968
Success
1668: 812781120811126785
Success
1669: 813051746834595840
Success
1670: 813066809284972545
Success
1671: 813081950185472002
Success
1672: 813096984823349248
Success
1673: 813112105746448384
Success
1674: 813127251579564032
Success
1675: 813142292504645637
Success
1676: 813157409116065792
Success
1677: 813172488309972993
Success
1678: 813187593374461952
Success
1679: 813202720496779264
Success
1680: 813217897535406080
Success
1681: 813800681631023104
Success
1682: 813812741911748608
Success
1683: 813910438903693312
Success
1684: 813944609378369540
Success
1685: 814153002265309185
Success
1686: 814530161257443328
Success
1687: 814638523311648768
Success
1688: 814986499976527872
Success
1689: 815390420867969024
Success
1690: 815639385530101762
Success
1691: 815736392542261248
Success
1692: 815966073409433600
Success
1693: 815990720817401858
Success
1694: 816014286006976512
Success
1695: 816091915477250048
Success
1696: 816336735214911488
Success
1697: 816450570814898180
Success
1698: 816697700272001025
Success
1699: 816816676327063552
Success
1700: 816829038950027264
Success
1701: 817056546584727552
Success
1702: 817120970343411712
Success
1703: 817171292965273600
Success
1704: 817181837579653120
Success
1705: 817415592588222464
Success
1706: 817423860136083457
Success
1707: 817536400337801217
Success
1708: 817777686764523521
Success
1709: 817827839487737858
Success
1710: 818145370475810820
Success
1711: 818259473185828864
Success
1712: 818536468981415936
Success
1713: 818588835076603904
Success
1714: 818614493328580609
Success
1715: 818627210458333184
Success
1716: 819004803107983360
Success
1717: 819006400881917954
Success
1718: 819015331746349057
Success
1719: 819015337530290176
Success
1720: 819227688460238848
Success
1721: 819347104292290561
Success
1722: 819588359383371776
Success
1723: 819711362133872643
Success
1724: 819924195358416896
Success
1725: 819952236453363712
Success
1726: 820078625395449857
Success
1727: 820314633777061888
Success
1728: 820446719150292993
Success
1729: 820690176645140481
Success
1730: 820749716845686786
Success
1731: 821044531881721856
Success
1732: 821107785811234820
Success
1733: 821149554670182400
Success
1734: 821407182352777218
Success
1735: 821522889702862852
Success
1736: 821765923262631936
Success
1737: 821813639212650496
Success
1738: 821886076407029760
Success
1739: 822244816520155136
Success
1740: 822462944365645825
Success
1741: 822489057087389700
Success
1742: 822610361945911296
Success
1743: 822647212903690241
Success
1744: 822859134160621569
Success
1745: 822872901745569793
Success
1746: 822975315408461824
Success
1747: 823269594223824897
Success
1748: 823322678127919110
Success
1749: 823581115634085888
Success
1750: 823699002998870016
Success
1751: 823939628516474880
Success
1752: 824297048279236611
Success
1753: 824325613288833024
Success
1754: 824663926340194305
Success
1755: 824775126675836928
Success
1756: 824796380199809024
Success
1757: 825026590719483904
Success
1758: 825147591692263424
Success
1759: 825535076884762624
Success
1760: 825829644528148480
Success
1761: 825876512159186944
Success
1762: 826115272272650244
Success
1763: 826204788643753985
Success
1764: 826240494070030336
Success
1765: 826476773533745153
Success
1766: 826598365270007810
Success
1767: 826848821049180160
Success
1768: 826958653328592898
Success
1769: 827199976799354881
Success
1770: 827324948884643840
Success
1771: 827600520311402496
Success
1772: 827653905312006145
Success
1773: 827933404142436356
Success
1774: 828011680017821696
Success
1775: 828046555563323392
Success
1776: 828372645993398273
Success
1777: 828376505180889089
Success
1778: 828381636999917570
Success
1779: 828408677031882754
Success
1780: 828409743546925057
Success
1781: 828650029636317184
Success
1782: 828708714936930305
Success
1783: 828770345708580865
Success
1784: 829011960981237760
Success
1785: 829141528400556032
Success
1786: 829374341691346946
Fail
1787: 829449946868879360
Success
1788: 829501995190984704
Success
1789: 829861396166877184
Success
1790: 829878982036299777
Success
1791: 830097400375152640
Success
1792: 830583320585068544
Success
1793: 830956169170665475
Success
1794: 831262627380748289
Success
1795: 831309418084069378
Success
1796: 831315979191906304
Success
1797: 831322785565769729
Success
1798: 831552930092285952
Success
1799: 831650051525054464
Success
1800: 831670449226514432
Success
1801: 831911600680497154

Rate limit reached. Sleeping for: 718

Success
1802: 831939777352105988
Success
1803: 832032802820481025
Success
1804: 832040443403784192
Success
1805: 832215726631055365
Success
1806: 832273440279240704
Success
1807: 832369877331693569
Success
1808: 832397543355072512
Success
1809: 832636094638288896
Success
1810: 832757312314028032
Success
1811: 832769181346996225
Success
1812: 832998151111966721
Success
1813: 833124694597443584
Success
1814: 833479644947025920
Success
1815: 833722901757046785
Success
1816: 833826103416520705
Success
1817: 833863086058651648
Success
1818: 834086379323871233
Success
1819: 834167344700198914
Success
1820: 834209720923721728
Success
1821: 834458053273591808
Success
1822: 834574053763584002
Success
1823: 834786237630337024
Success
1824: 834931633769889797
Success
1825: 835152434251116546
Success
1826: 835172783151792128
Success
1827: 835264098648616962
Success
1828: 835297930240217089
Success
1829: 835574547218894849
Success
1830: 836001077879255040
Success
1831: 836260088725786625
Success
1832: 836380477523124226
Success
1833: 836677758902222849
Success
1834: 836753516572119041
Success
1835: 836989968035819520
Success
1836: 837012587749474308
Fail
1837: 837110210464448512
Success
1838: 837366284874571778
Fail
1839: 837471256429613056
Success
1840: 837482249356513284
Success
1841: 837820167694528512
Success
1842: 838083903487373313
Success
1843: 838476387338051585
Success
1844: 838561493054533637
Success
1845: 838916489579200512
Success
1846: 838921590096166913
Success
1847: 839239871831150596
Success
1848: 839290600511926273
Success
1849: 839549326359670784
Success
1850: 839990271299457024
Success
1851: 840268004936019968
Success
1852: 840370681858686976
Success
1853: 840632337062862849
Success
1854: 840696689258311684
Success
1855: 841077006473256960
Success
1856: 841314665196081154
Success
1857: 841439858740625411
Success
1858: 841680585030541313
Success
1859: 841833993020538882
Success
1860: 842115215311396866
Success
1861: 842163532590374912
Success
1862: 842535590457499648
Success
1863: 842765311967449089
Success
1864: 842846295480000512
Success
1865: 842892208864923648
Fail
1866: 843235543001513987
Success
1867: 843604394117681152
Success
1868: 843856843873095681
Success
1869: 844223788422217728
Success
1870: 844580511645339650
Success
1871: 844704788403113984
Fail
1872: 844973813909606400
Success
1873: 844979544864018432
Success
1874: 845306882940190720
Success
1875: 845397057150107648
Success
1876: 845677943972139009
Success
1877: 845812042753855489
Success
1878: 846042936437604353
Success
1879: 846153765933735936
Success
1880: 846514051647705089
Success
1881: 846874817362120707
Success
1882: 847116187444137987
Success
1883: 847157206088847362
Success
1884: 847251039262605312
Success
1885: 847606175596138505
Success
1886: 847842811428974592
Success
1887: 847962785489326080
Success
1888: 847971574464610304
Success
1889: 848212111729840128
Success
1890: 848324959059550208
Success
1891: 848690551926992896
Success
1892: 849051919805034497
Success
1893: 849336543269576704
Success
1894: 849412302885593088
Success
1895: 849776966551130114
Success
1896: 850019790995546112
Success
1897: 850145622816686080
Success
1898: 850380195714523136
Success
1899: 850753642995093505
Success
1900: 851224888060895234
Success
1901: 851464819735769094
Success
1902: 851591660324737024
Success
1903: 851861385021730816
Success
1904: 851953902622658560
Fail
1905: 852189679701164033
Success
1906: 852226086759018497
Success
1907: 852311364735569921
Success
1908: 852553447878664193
Success
1909: 852672615818899456
Success
1910: 852912242202992640
Success
1911: 853299958564483072
Success
1912: 853639147608842240
Success
1913: 853760880890318849
Success
1914: 854010172552949760
Success
1915: 854120357044912130
Success
1916: 854365224396361728
Success
1917: 854482394044301312
Success
1918: 854732716440526848
Success
1919: 855459453768019968
Success
1920: 855851453814013952
Success
1921: 856282028240666624
Success
1922: 856526610513747968
Success
1923: 856543823941562368
Success
1924: 857029823797047296
Success
1925: 857263160327368704
Success
1926: 857393404942143489
Success
1927: 857746408056729600
Success
1928: 857989990357356544
Success
1929: 858107933456039936
Success
1930: 858471635011153920
Success
1931: 858843525470990336
Success
1932: 859074603037188101
Success
1933: 859196978902773760
Success
1934: 859607811541651456
Success
1935: 859851578198683649
Success
1936: 859924526012018688
Success
1937: 860184849394610176
Success
1938: 860276583193509888
Success
1939: 860524505164394496
Success
1940: 860563773140209665
Success
1941: 860924035999428608
Success
1942: 861005113778896900
Success
1943: 861288531465048066
Success
1944: 861383897657036800
Success
1945: 861769973181624320
Fail
1946: 862096992088072192
Success
1947: 862457590147678208
Success
1948: 862722525377298433
Success
1949: 862831371563274240
Success
1950: 863062471531167744
Success
1951: 863079547188785154
Success
1952: 863432100342583297
Success
1953: 863553081350529029
Success
1954: 863907417377173506
Success
1955: 864197398364647424
Success
1956: 864279568663928832
Success
1957: 864873206498414592
Success
1958: 865006731092295680
Success
1959: 865359393868664832
Success
1960: 865718153858494464
Success
1961: 866334964761202691
Success
1962: 866450705531457537
Success
1963: 866686824827068416
Success
1964: 867051520902168576
Success
1965: 867072653475098625
Success
1966: 867421006826221569
Success
1967: 867774946302451713
Success
1968: 867900495410671616
Success
1969: 868552278524837888
Success
1970: 868622495443632128
Success
1971: 868880397819494401
Success
1972: 869227993411051520
Success
1973: 869596645499047938
Success
1974: 869702957897576449
Success
1975: 869772420881756160
Success
1976: 870063196459192321
Success
1977: 870308999962521604
Success
1978: 870374049280663552
Success
1979: 870656317836468226
Success
1980: 870804317367881728
Success
1981: 871032628920680449
Success
1982: 871515927908634625
Success
1983: 871762521631449091
Success
1984: 871879754684805121
Success
1985: 872122724285648897
Success
1986: 872261713294495745
Fail
1987: 872486979161796608
Success
1988: 872620804844003328
Success
1989: 872820683541237760
Success
1990: 872967104147763200
Success
1991: 873213775632977920
Success
1992: 873580283840344065
Success
1993: 873697596434513921
Fail
1994: 874012996292530176
Success
1995: 874057562936811520
Success
1996: 874296783580663808
Success
1997: 874680097055178752
Success
1998: 875021211251597312
Success
1999: 875144289856114688
Success
2000: 875747767867523072
Success
2001: 876120275196170240
Success
2002: 876484053909872640
Success
2003: 876838120628539392
Success
2004: 877201837425926144
Success
2005: 877316821321428993
Success
2006: 877556246731214848
Success
2007: 877611172832227328
Success
2008: 877736472329191424
Success
2009: 878057613040115712
Success
2010: 878281511006478336
Success
2011: 878776093423087618
Success
2012: 879008229531029506
Success
2013: 879050749262655488
Success
2014: 879376492567855104
Success
2015: 879415818425184262
Success
2016: 879492040517615616
Success
2017: 879862464715927552
Success
2018: 880095782870896641
Success
2019: 880221127280381952
Success
2020: 880465832366813184
Success
2021: 880872448815771648
Success
2022: 880935762899988482
Success
2023: 881268444196462592
Success
2024: 881536004380872706
Success
2025: 881666595344535552
Success
2026: 881906580714921986
Success
2027: 882045870035918850
Success
2028: 882268110199369728
Success
2029: 882627270321602560
Success
2030: 882762694511734784
Success
2031: 882992080364220416
Success
2032: 883117836046086144
Success
2033: 883360690899218434
Success
2034: 883482846933004288
Success
2035: 883838122936631299
Success
2036: 884162670584377345
Success
2037: 884441805382717440
Success
2038: 884562892145688576
Success
2039: 884876753390489601
Success
2040: 884925521741709313
Success
2041: 885167619883638784
Success
2042: 885311592912609280
Success
2043: 885528943205470208
Success
2044: 885984800019947520
Success
2045: 886258384151887873
Success
2046: 886366144734445568
Success
2047: 886680336477933568
Success
2048: 886736880519319552
Success
2049: 886983233522544640
Success
2050: 887101392804085760

Success
2051: 887343217045368832
Success
2052: 887473957103951883
Success
2053: 887517139158093824
Success
2054: 887705289381826560
Success
2055: 888078434458587136
Success
2056: 888202515573088257
Fail
2057: 888554962724278272
Success
2058: 888804989199671297
Success
2059: 888917238123831296
Success
2060: 889278841981685760
Success
2061: 889531135344209921
Success
2062: 889638837579907072
Success
2063: 889665388333682689
Success
2064: 889880896479866881
Success
2065: 890006608113172480
Success
2066: 890240255349198849
Success
2067: 890609185150312448
Success
2068: 890729181411237888
Success
2069: 890971913173991426
Success
2070: 891087950875897856
Success
2071: 891327558926688256
Success
2072: 891689557279858688
Success
2073: 891815181378084864
Success
2074: 892177421306343426
Success
2075: 892420643555336193
Success
1857.2004252999977
{'680055455951884288': TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), '754011816964026368': TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), '759566828574212096': TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), '771004394259247104': TweepError([{'code': 179, 'message': 'Sorry, you are not authorized to see this status.'}]), '779123168116150273': TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), '802247111496568832': TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), '829374341691346946': TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), '837012587749474308': TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), '837366284874571778': TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), '842892208864923648': TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), '844704788403113984': TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), '851953902622658560': TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), '861769973181624320': TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), '872261713294495745': TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), '873697596434513921': TweepError([{'code': 144, 'message': 'No status found with that ID.'}]), '888202515573088257': TweepError([{'code': 144, 'message': 'No status found with that ID.'}])}

In [50]:
my_list_of_dicts = []
for each_json_tweet in tweet:
    my_list_of_dicts.append(each_json_tweet._json)

TypeError: 'Status' object is not iterable

In [321]:
all_data=[]
my_demo_list = []
for json_file in open('tweet_json.txt', encoding='utf-8'):  
    all_data.append(json.loads(json_file))

In [322]:
for each_dictionary in all_data:
        tweet_id = each_dictionary['id']
        text = each_dictionary['full_text']
        favorite_count = each_dictionary['favorite_count']
        retweet_count = each_dictionary['retweet_count']
        created_at = each_dictionary['created_at']
        my_demo_list.append({'tweet_id': str(tweet_id),
                             'text': str(text),
                             'favorite_count': int(favorite_count),
                             'retweet_count': int(retweet_count),
                             'created_at': created_at,
                            })
        #print(my_demo_list)
        tweet_json = pd.DataFrame(my_demo_list, columns = 
                                  ['tweet_id', 'text', 
                                   'favorite_count', 'retweet_count', 
                                   'created_at'])

In [323]:
tweet_json.head(2)

,tweet_id,text,favorite_count,retweet_count,created_at
0,666020888022790149,Here we have a Japanese Irish Setter. Lost eye...,2388,458,Sun Nov 15 22:32:08 +0000 2015
1,666029285002620928,This is a western brown Mitsubishi terrier. Up...,120,42,Sun Nov 15 23:05:30 +0000 2015

In [324]:
img_prediction = df
img_prediction.head(2)

,tweet_id,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog
1,666020888022790149,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,1,Welsh_springer_spaniel,0.465074,True,collie,0.156665,True,Shetland_sheepdog,0.0614285,True
2,666029285002620928,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,1,redbone,0.506826,True,miniature_pinscher,0.07419169999999999,True,Rhodesian_ridgeback,0.07201,True

In [368]:
twitter_data = pd.read_csv('./twitter-archive-enhanced.csv')
twitter_data.head(2)

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
0,892420643555336193,NaN,NaN,2017-08-01 16:23:56 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Phineas. He's a mystical boy. Only eve...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,None,None,None,None
1,892177421306343426,NaN,NaN,2017-08-01 00:17:27 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Tilly. She's just checking pup on you....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,None,None,None,None

In [378]:
twitter_data['dog_type']= twitter_data["doggo"]+twitter_data["floofer"]+twitter_data["pupper"]+twitter_data["puppo"]
twitter_data['dog_type'] = twitter_data.dog_type.str.replace("None","")
twitter_data.drop(columns = ["doggo","floofer","pupper","puppo"])
twitter_data[twitter_data["dog_type"]!=""].head(3)

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo,dog_type
9,890240255349198849,NaN,NaN,2017-07-26 15:59:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Cassie. She is a college pup. Studying...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/890240255...,14,10,Cassie,doggo,None,None,None,doggo
12,889665388333682689,NaN,NaN,2017-07-25 01:55:32 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here's a puppo that seems to be on the fence a...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/889665388...,13,10,None,None,None,None,puppo,puppo
14,889531135344209921,NaN,NaN,2017-07-24 17:02:04 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Stuart. He's sporting his favorite fan...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/889531135...,13,10,Stuart,None,None,None,puppo,puppo

In [379]:
twitter_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2356 entries, 0 to 2355
Data columns (total 18 columns):
tweet_id                      2356 non-null int64
in_reply_to_status_id         78 non-null float64
in_reply_to_user_id           78 non-null float64
timestamp                     2356 non-null object
source                        2356 non-null object
text                          2356 non-null object
retweeted_status_id           181 non-null float64
retweeted_status_user_id      181 non-null float64
retweeted_status_timestamp    181 non-null object
expanded_urls                 2297 non-null object
rating_numerator              2356 non-null int64
rating_denominator            2356 non-null int64
name                          2356 non-null object
doggo                         2356 non-null object
floofer                       2356 non-null object
pupper                        2356 non-null object
puppo                         2356 non-null object
dog_type                      2356 non-null object
dtypes: float64(4), int64(3), object(11)
memory usage: 331.4+ KB

In [380]:
twitter_data.describe()

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,retweeted_status_id,retweeted_status_user_id,rating_numerator,rating_denominator
count,2.356000e+03,7.800000e+01,7.800000e+01,1.810000e+02,1.810000e+02,2356.000000,2356.000000
mean,7.427716e+17,7.455079e+17,2.014171e+16,7.720400e+17,1.241698e+16,13.126486,10.455433
std,6.856705e+16,7.582492e+16,1.252797e+17,6.236928e+16,9.599254e+16,45.876648,6.745237
min,6.660209e+17,6.658147e+17,1.185634e+07,6.661041e+17,7.832140e+05,0.000000,0.000000
25%,6.783989e+17,6.757419e+17,3.086374e+08,7.186315e+17,4.196984e+09,10.000000,10.000000
50%,7.196279e+17,7.038708e+17,4.196984e+09,7.804657e+17,4.196984e+09,11.000000,10.000000
75%,7.993373e+17,8.257804e+17,4.196984e+09,8.203146e+17,4.196984e+09,12.000000,10.000000
max,8.924206e+17,8.862664e+17,8.405479e+17,8.874740e+17,7.874618e+17,1776.000000,170.000000

In [381]:
twitter_data.isnull()

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo,dog_type
0,False,True,True,False,False,False,True,True,True,False,False,False,False,False,False,False,False,False
1,False,True,True,False,False,False,True,True,True,False,False,False,False,False,False,False,False,False
2,False,True,True,False,False,False,True,True,True,False,False,False,False,False,False,False,False,False
3,False,True,True,False,False,False,True,True,True,False,False,False,False,False,False,False,False,False
4,False,True,True,False,False,False,True,True,True,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2351,False,True,True,False,False,False,True,True,True,False,False,False,False,False,False,False,False,False
2352,False,True,True,False,False,False,True,True,True,False,False,False,False,False,False,False,False,False
2353,False,True,True,False,False,False,True,True,True,False,False,False,False,False,False,False,False,False
2354,False,True,True,False,False,False,True,True,True,False,False,False,False,False,False,False,False,False
2355,False,True,True,False,False,False,True,True,True,False,False,False,False,False,False,False,False,False

In [382]:
twitter_data.head()

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo,dog_type
0,892420643555336193,NaN,NaN,2017-08-01 16:23:56 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Phineas. He's a mystical boy. Only eve...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,None,None,None,None,
1,892177421306343426,NaN,NaN,2017-08-01 00:17:27 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Tilly. She's just checking pup on you....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,None,None,None,None,
2,891815181378084864,NaN,NaN,2017-07-31 00:18:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Archie. He is a rare Norwegian Pouncin...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891815181...,12,10,Archie,None,None,None,None,
3,891689557279858688,NaN,NaN,2017-07-30 15:58:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Darla. She commenced a snooze mid meal...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891689557...,13,10,Darla,None,None,None,None,
4,891327558926688256,NaN,NaN,2017-07-29 16:00:24 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Franklin. He would like you to stop ca...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891327558...,12,10,Franklin,None,None,None,None,

In [383]:
twitter_data[twitter_data.retweeted_status_id.notnull()].head(2)

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo,dog_type
19,888202515573088257,NaN,NaN,2017-07-21 01:02:36 +0000,"<a href=""http://twitter.com/download/iphone"" r...",RT @dog_rates: This is Canela. She attempted s...,8.874740e+17,4.196984e+09,2017-07-19 00:47:34 +0000,https://twitter.com/dog_rates/status/887473957...,13,10,Canela,None,None,None,None,
32,886054160059072513,NaN,NaN,2017-07-15 02:45:48 +0000,"<a href=""http://twitter.com/download/iphone"" r...",RT @Athletics: 12/10 #BATP https://t.co/WxwJmv...,8.860537e+17,1.960740e+07,2017-07-15 02:44:07 +0000,https://twitter.com/dog_rates/status/886053434...,12,10,None,None,None,None,None,

In [384]:
twitter_data[twitter_data.retweeted_status_id.notnull()].head(2)

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo,dog_type
19,888202515573088257,NaN,NaN,2017-07-21 01:02:36 +0000,"<a href=""http://twitter.com/download/iphone"" r...",RT @dog_rates: This is Canela. She attempted s...,8.874740e+17,4.196984e+09,2017-07-19 00:47:34 +0000,https://twitter.com/dog_rates/status/887473957...,13,10,Canela,None,None,None,None,
32,886054160059072513,NaN,NaN,2017-07-15 02:45:48 +0000,"<a href=""http://twitter.com/download/iphone"" r...",RT @Athletics: 12/10 #BATP https://t.co/WxwJmv...,8.860537e+17,1.960740e+07,2017-07-15 02:44:07 +0000,https://twitter.com/dog_rates/status/886053434...,12,10,None,None,None,None,None,

In [393]:
# Drop Retweets
twitter_data_clean = twitter_data[~twitter_data.text.str.startswith("RT @")]
twitter_data_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2175 entries, 0 to 2355
Data columns (total 18 columns):
tweet_id                      2175 non-null int64
in_reply_to_status_id         78 non-null float64
in_reply_to_user_id           78 non-null float64
timestamp                     2175 non-null object
source                        2175 non-null object
text                          2175 non-null object
retweeted_status_id           0 non-null float64
retweeted_status_user_id      0 non-null float64
retweeted_status_timestamp    0 non-null object
expanded_urls                 2117 non-null object
rating_numerator              2175 non-null int64
rating_denominator            2175 non-null int64
name                          2175 non-null object
doggo                         2175 non-null object
floofer                       2175 non-null object
pupper                        2175 non-null object
puppo                         2175 non-null object
dog_type                      2175 non-null object
dtypes: float64(4), int64(3), object(11)
memory usage: 322.9+ KB

In [394]:
#Remove replied to the tweets
twitter_data_clean = twitter_data_clean[~twitter_data_clean.in_reply_to_status_id.notnull()]
twitter_data_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2097 entries, 0 to 2355
Data columns (total 18 columns):
tweet_id                      2097 non-null int64
in_reply_to_status_id         0 non-null float64
in_reply_to_user_id           0 non-null float64
timestamp                     2097 non-null object
source                        2097 non-null object
text                          2097 non-null object
retweeted_status_id           0 non-null float64
retweeted_status_user_id      0 non-null float64
retweeted_status_timestamp    0 non-null object
expanded_urls                 2094 non-null object
rating_numerator              2097 non-null int64
rating_denominator            2097 non-null int64
name                          2097 non-null object
doggo                         2097 non-null object
floofer                       2097 non-null object
pupper                        2097 non-null object
puppo                         2097 non-null object
dog_type                      2097 non-null object
dtypes: float64(4), int64(3), object(11)
memory usage: 311.3+ KB

In [395]:
twitter_data_clean = twitter_data_clean[['tweet_id','timestamp','text','expanded_urls','rating_numerator','rating_denominator','name','dog_type']]
twitter_data_clean.head(2)

,tweet_id,timestamp,text,expanded_urls,rating_numerator,rating_denominator,name,dog_type
0,892420643555336193,2017-08-01 16:23:56 +0000,This is Phineas. He's a mystical boy. Only eve...,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,
1,892177421306343426,2017-08-01 00:17:27 +0000,This is Tilly. She's just checking pup on you....,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,

In [404]:
#Remove data where ratina Denom is not equal to 10 (which doesn't make sense as the ratinf standard id out of 10.
twitter_data_clean = twitter_data_clean[twitter_data_clean["rating_denominator"]==10]
twitter_data_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2080 entries, 0 to 2355
Data columns (total 8 columns):
tweet_id              2080 non-null int64
timestamp             2080 non-null object
text                  2080 non-null object
expanded_urls         2077 non-null object
rating_numerator      2080 non-null int64
rating_denominator    2080 non-null int64
name                  2080 non-null object
dog_type              2080 non-null object
dtypes: int64(3), object(5)
memory usage: 146.2+ KB

In [406]:
#For now Remove data where ratina Numerator is huge (which motlikely is due to a decimal point)
twitter_data_clean = twitter_data_clean[twitter_data_clean["rating_numerator"]<=15]

In [407]:
twitter_data_clean.head()

,tweet_id,timestamp,text,expanded_urls,rating_numerator,rating_denominator,name,dog_type
0,892420643555336193,2017-08-01 16:23:56 +0000,This is Phineas. He's a mystical boy. Only eve...,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,
1,892177421306343426,2017-08-01 00:17:27 +0000,This is Tilly. She's just checking pup on you....,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,
2,891815181378084864,2017-07-31 00:18:03 +0000,This is Archie. He is a rare Norwegian Pouncin...,https://twitter.com/dog_rates/status/891815181...,12,10,Archie,
3,891689557279858688,2017-07-30 15:58:51 +0000,This is Darla. She commenced a snooze mid meal...,https://twitter.com/dog_rates/status/891689557...,13,10,Darla,
4,891327558926688256,2017-07-29 16:00:24 +0000,This is Franklin. He would like you to stop ca...,https://twitter.com/dog_rates/status/891327558...,12,10,Franklin,

In [416]:
tweet_json.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2059 entries, 0 to 2058
Data columns (total 5 columns):
tweet_id          2059 non-null object
text              2059 non-null object
favorite_count    2059 non-null int64
retweet_count     2059 non-null int64
created_at        2059 non-null object
dtypes: int64(2), object(3)
memory usage: 80.6+ KB

In [418]:
#change ID format to join it with Twitter_data
tweet_json.tweet_id = tweet_json.tweet_id.astype(np.int64)

In [426]:
#Merge twitter_data_clean and tweet_json to get the Favorite count & Retweet Count added. 
#Did a left join to keep those records in Twitter Data even if there was no info retrieved for some of the Twitter IDs from Twitter API

twitter_data_clean = pd.merge(twitter_data_clean, tweet_json[['tweet_id','retweet_count','favorite_count']],on=['tweet_id'], how='left')

In [429]:
twitter_data_clean.head()

,tweet_id,timestamp,text,expanded_urls,rating_numerator,rating_denominator,name,dog_type,retweet_count,favorite_count
0,892420643555336193,2017-08-01 16:23:56 +0000,This is Phineas. He's a mystical boy. Only eve...,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,,7596.0,35858.0
1,892177421306343426,2017-08-01 00:17:27 +0000,This is Tilly. She's just checking pup on you....,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,,5626.0,30933.0
2,891815181378084864,2017-07-31 00:18:03 +0000,This is Archie. He is a rare Norwegian Pouncin...,https://twitter.com/dog_rates/status/891815181...,12,10,Archie,,3721.0,23286.0
3,891689557279858688,2017-07-30 15:58:51 +0000,This is Darla. She commenced a snooze mid meal...,https://twitter.com/dog_rates/status/891689557...,13,10,Darla,,7764.0,39115.0
4,891327558926688256,2017-07-29 16:00:24 +0000,This is Franklin. He would like you to stop ca...,https://twitter.com/dog_rates/status/891327558...,12,10,Franklin,,8371.0,37361.0

In [431]:
img_prediction.head(5)

,tweet_id,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog
1,666020888022790149,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,1,Welsh_springer_spaniel,0.465074,True,collie,0.156665,True,Shetland_sheepdog,0.0614285,True
2,666029285002620928,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,1,redbone,0.506826,True,miniature_pinscher,0.07419169999999999,True,Rhodesian_ridgeback,0.07201,True
3,666033412701032449,https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg,1,German_shepherd,0.596461,True,malinois,0.13858399999999998,True,bloodhound,0.11619700000000001,True
4,666044226329800704,https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg,1,Rhodesian_ridgeback,0.408143,True,redbone,0.360687,True,miniature_pinscher,0.222752,True
5,666049248165822465,https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg,1,miniature_pinscher,0.560311,True,Rottweiler,0.243682,True,Doberman,0.154629,True

In [464]:
img_prediction_clean_melt1 = pd.melt(img_prediction, id_vars=['tweet_id', 'jpg_url', 'img_num'],
                           value_vars=['p1','p2','p3'], var_name='prediction', value_name='pred_val')

img_prediction_clean_melt2 = pd.melt(img_prediction, id_vars=['tweet_id', 'jpg_url', 'img_num'],
                           value_vars=['p1_conf','p2_conf','p3_conf'], var_name='prediction', value_name='pred_conf')

img_prediction_clean_melt2.prediction = img_prediction_clean_melt2.prediction.str[:2]
img_prediction_clean_melt3 = pd.melt(img_prediction, id_vars=['tweet_id', 'jpg_url', 'img_num'],
                           value_vars=['p1_dog','p3_dog','p3_dog'], var_name='prediction', value_name='pred_accuracy')

img_prediction_clean_melt3.prediction = img_prediction_clean_melt3.prediction.str[:2]

In [469]:
img_prediction_clean_melt = img_prediction_clean_melt1.merge(img_prediction_clean_melt2,on=['tweet_id','img_num','jpg_url','prediction'])
img_prediction_clean_melt = img_prediction_clean_melt.merge(img_prediction_clean_melt3,on=['tweet_id','img_num','jpg_url','prediction'])

In [472]:
img_prediction_clean_melt.head(5)

,tweet_id,jpg_url,img_num,prediction,pred_val,pred_conf,pred_accuracy
0,666020888022790149,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,1,p1,Welsh_springer_spaniel,0.465074,True
1,666029285002620928,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,1,p1,redbone,0.506826,True
2,666033412701032449,https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg,1,p1,German_shepherd,0.596461,True
3,666044226329800704,https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg,1,p1,Rhodesian_ridgeback,0.408143,True
4,666049248165822465,https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg,1,p1,miniature_pinscher,0.560311,True

In [480]:
#Removing wrong/False prediction (e.g. in one instance "paper Towel" was predicted as a dog breed.)
img_prediction_clean_melt = img_prediction_clean_melt[img_prediction_clean_melt.pred_accuracy=='True']
img_prediction_clean_melt.shape

(4530, 7)

In [506]:
#Remove duplicate records
img_prediction_clean_melt = img_prediction_clean_melt.drop_duplicates()
img_prediction_clean_melt.shape

(1638, 4)

In [508]:
grouped = img_prediction_clean_melt.groupby(['tweet_id', 'jpg_url', 'img_num','prediction']).sum().reset_index()
grouped_sorted = grouped.sort_values('pred_conf', ascending=False)

img_prediction_clean_melted = grouped_sorted.groupby(['tweet_id', 'jpg_url', 'img_num']).first().reset_index()
img_prediction_clean_melted.shape

(1638, 7)

In [509]:
img_prediction_clean_melted.head(2)

,tweet_id,jpg_url,img_num,prediction,pred_val,pred_conf,pred_accuracy
0,666020888022790149,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,1,p1,Welsh_springer_spaniel,0.465074,True
1,666029285002620928,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,1,p1,redbone,0.506826,True

In [510]:
twitter_data_clean.head(2)

,tweet_id,timestamp,text,expanded_urls,rating_numerator,rating_denominator,name,dog_type,retweet_count,favorite_count
0,892420643555336193,2017-08-01 16:23:56 +0000,This is Phineas. He's a mystical boy. Only eve...,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,,7596.0,35858.0
1,892177421306343426,2017-08-01 00:17:27 +0000,This is Tilly. She's just checking pup on you....,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,,5626.0,30933.0